USE [master]
GO
/****** Object:  Database [Webi]    Script Date: 7/16/2020 3:01:19 PM ******/
CREATE DATABASE [Webi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Webi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Webi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Webi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Webi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Webi] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Webi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Webi] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Webi] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Webi] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Webi] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Webi] SET ARITHABORT OFF 
GO
ALTER DATABASE [Webi] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Webi] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Webi] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Webi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Webi] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Webi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Webi] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Webi] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Webi] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Webi] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Webi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Webi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Webi] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Webi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Webi] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Webi] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Webi] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Webi] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Webi] SET  MULTI_USER 
GO
ALTER DATABASE [Webi] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Webi] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Webi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Webi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Webi] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Webi', N'ON'
GO
ALTER DATABASE [Webi] SET QUERY_STORE = OFF
GO
USE [Webi]
GO
/****** Object:  Table [dbo].[Perdoruesi]    Script Date: 7/16/2020 3:01:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Perdoruesi](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](50) NULL,
	[Email] [varchar](150) NULL,
	[Password] [varchar](550) NULL,
	[Birthday] [date] NULL,
 CONSTRAINT [PK_Perdoruesi] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Post]    Script Date: 7/16/2020 3:01:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Post](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Src] [varchar](255) NULL,
	[Para] [varchar](150) NULL,
 CONSTRAINT [PK_Post] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Post]    Script Date: 7/16/2020 3:01:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contact](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NULL,
	[Email] [varchar](150) NULL,
	[Subject][varchar](255)null,
	[Message][text]null,
 CONSTRAINT [PK_Contact] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Webi] SET  READ_WRITE 
GO

